spring.application.name=springa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=springuser1
spring.datasource.password=1234
spring.datasource.url=jdbc:mysql://localhost:3306/producta
spring.jpa.hibernate.ddl-auto=update
server.port=8008